### ISSUE TITLE
脚本运行完成后会出现一个报错

### ISSUE THREAD

**Issue by ShiFangJuMie** [wang-st/aliyunSignIn#1]
## 开始执行... 2024-01-19 15:18:19

省略

/ql/data/scripts/node_modules/got:1
.pnpm/got@11.8.6/node_modules/got
^

SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.initGotEnv (/ql/data/scripts/wang-st_aliyunSignIn/sendNotify.js:1116:3028)
    at Object.post (/ql/data/scripts/wang-st_aliyunSignIn/sendNotify.js:1116:4473)

Node.js v18.18.2

## 执行结束... 2024-01-19 15:18:26  耗时 7 秒

**Comment by wang-st** [comment]
依赖问题 请重新安装依赖包

**Comment by ShiFangJuMie** [comment]
> 依赖问题 请重新安装依赖包

感谢回复。我也有过这样的猜测，重装axios并没有解决这个问题。

运行环境是docker部署最新版的青龙v2.17.0（今天刚更新的）

以下是日志

日志 - axios
开始安装依赖 axios，开始时间 2024-01-19 15:22:53

Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 4, reused 3, downloaded 0, added 0
Progress: resolved 5, reused 3, downloaded 0, added 0
Progress: resolved 8, reused 8, downloaded 0, added 0
Already up to date
 WARN  axios has no binaries
Progress: resolved 9, reused 9, downloaded 0, added 0, done

Done in 1m 1.4s

依赖安装成功，结束时间 2024-01-19 15:23:55，耗时 61 秒

开始安装依赖 qlapi，开始时间 2024-01-19 14:50:01

检测到已经安装 qlapi

Name: qlapi
Version: 0.1.5.1
Summary: Api for use quanlan device
Home-page: Author: eegion
Author-email: hehuajun@eegion.com
License: 
Location: /usr/local/lib/python3.11/site-packages
Requires: 
Required-by:

跳过安装

依赖安装成功，结束时间 2024-01-19 14:50:03，耗时 1 秒

**Comment by wang-st** [comment]
升级下 got
